GET http://localhost:5000/conspiracies

###

GET http://localhost:5000/conspiracies/6a1c879527c3fb3aadabc114

###
POST http://localhost:5000/conspiracies
Content-Type: application/json

{
    "text":"cosnpiracy"
}

###
DELETE http://localhost:5000/conspiracies/6a1d32e8579ab374642c59eb

###
PATCH http://localhost:5000/conspiracies/6a1c88af206015279f313410
Content-Type: application/json

{
    "text":"new cosnpiracy",
    "likes":12
}

###
POST http://localhost:5000/conspiracies/6a1d9caf59a6b5a0482f793c/like

###
POST http://localhost:5000/conspiracies/6a1d32e8579ab374642c59eb/disLike

###
POST http://localhost:5000/conspiracies/6a1c88af206015279f313410/comment
Content-Type: application/json

{
    "text":"new comment",
    "author": "yahel"
}

### Get all sorted by date
GET http://localhost:5000/conspiracies?sort=likes

### 
POST http://localhost:5000/conspiracies/generate
Content-Type: application/json

{

}