GET http://localhost:3000/conspiracys

###

GET http://localhost:3000/conspiracys/6a1c879527c3fb3aadabc114

###
POST http://localhost:3000/conspiracys
Content-Type: application/json

{
    "text":"cosnpiracy"
}

###
DELETE http://localhost:3000/conspiracys/6a1c879527c3fb3aadabc114

###
PATCH http://localhost:3000/conspiracys/6a1c88af206015279f313410
Content-Type: application/json

{
    "text":"new cosnpiracy",
    "likes":12
}

###
POST http://localhost:3000/conspiracys/6a1d32e8579ab374642c59eb/like

###
POST http://localhost:3000/conspiracys/6a1c88af206015279f313410/disLike

###
POST http://localhost:3000/conspiracys/6a1c88af206015279f313410/comment
Content-Type: application/json

{
    "text":"new comment",
    "author": "yahel"
}

### Get all sorted by date
GET http://localhost:3000/conspiracys?sort=likes

### 
POST http://localhost:3000/conspiracys/generate
Content-Type: application/json

{

}